// frontend/src/components/ui/label/Label.vue
<template>
  <RekaLabel
    :for="forId"
    :class="cn(
      'text-sm font-medium leading-none text-[hsl(var(--foreground))]',
      'peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
      props.class,
    )"
  >
    <slot />
  </RekaLabel>
</template>

<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { Label as RekaLabel } from 'reka-ui'
import { cn } from '@/lib/utils'

const props = defineProps<{
  forId?: string
  class?: HTMLAttributes['class']
}>()
</script>

// frontend/src/console/react/ui/label.tsx
import * as React from 'react'
import { cn } from '../lib/utils'

const Label = React.forwardRef<HTMLLabelElement, React.LabelHTMLAttributes<HTMLLabelElement>>(({ className, ...props }, ref) => React.createElement('label', {
  ...props,
  ref,
  className: cn('text-sm font-medium leading-none text-[hsl(var(--foreground))] peer-disabled:cursor-not-allowed peer-disabled:opacity-70', className),
}))

Label.displayName = 'Label'

export { Label }
