// frontend/src/components/ui/textarea/Textarea.vue
<template>
  <textarea
    v-bind="$attrs"
    :value="modelValue"
    :class="cn(
      'flex min-h-24 w-full rounded-[var(--ui-radius)] border border-[hsl(var(--input))]',
      'bg-[hsl(var(--background))] px-3 py-2 text-sm text-[hsl(var(--foreground))] shadow-sm',
      'placeholder:text-[hsl(var(--muted-foreground))]',
      'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring))] focus-visible:ring-offset-2',
      'focus-visible:ring-offset-[hsl(var(--background))]',
      'disabled:cursor-not-allowed disabled:opacity-50',
      props.class,
    )"
    @input="onInput"
  />
</template>

<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  modelValue?: string | number | null
  class?: HTMLAttributes['class']
}>()

const emit = defineEmits<{
  (event: 'update:modelValue', value: string): void
}>()

function onInput(event: Event) {
  emit('update:modelValue', (event.target as HTMLTextAreaElement).value)
}
</script>

// frontend/src/console/react/ui/textarea.tsx
import * as React from 'react'
import { cn } from '../lib/utils'

const Textarea = React.forwardRef<HTMLTextAreaElement, React.TextareaHTMLAttributes<HTMLTextAreaElement>>(({ className, ...props }, ref) => {
  const cleaned = className?.replace(/\binput(?:-[a-z-]+)?\b/g, ' ')
  return React.createElement('textarea', {
    ...props,
    ref,
    className: cn(
      'flex min-h-24 w-full resize-y rounded-[var(--ui-radius)] border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 py-2 text-sm text-[hsl(var(--foreground))] shadow-sm outline-none transition-colors placeholder:text-[hsl(var(--muted-foreground))] focus-visible:border-[hsl(var(--ring))] focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring)/.18)] disabled:cursor-not-allowed disabled:opacity-50',
      cleaned,
    ),
  })
})

Textarea.displayName = 'Textarea'

export { Textarea }
