// frontend/src/console/react/ui/input.tsx
import * as React from 'react'
import { cn } from '../lib/utils'

const Input = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement>>(({ className, type = 'text', ...props }, ref) => {
  const isChoice = type === 'checkbox' || type === 'radio'
  const cleaned = className?.replace(/\binput(?:-[a-z-]+)?\b/g, ' ')
  return React.createElement('input', {
    ...props,
    ref,
    type,
    className: cn(
      isChoice
        ? 'h-4 w-4 shrink-0 rounded border-[hsl(var(--border))] accent-[hsl(var(--primary))]'
        : 'flex h-10 w-full rounded-[var(--ui-radius)] border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 py-2 text-sm text-[hsl(var(--foreground))] shadow-sm outline-none transition-colors placeholder:text-[hsl(var(--muted-foreground))] focus-visible:border-[hsl(var(--ring))] focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring)/.18)] disabled:cursor-not-allowed disabled:opacity-50',
      cleaned,
    ),
  })
})

Input.displayName = 'Input'

export { Input }

// frontend/src/components/ui/input/Input.vue
<template>
  <input
    v-bind="$attrs"
    :value="modelValue"
    :class="cn(
      'flex h-[var(--ui-control-height)] w-full rounded-[var(--ui-radius)]',
      'border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 py-2 text-sm',
      'text-[hsl(var(--foreground))] shadow-sm transition-[border-color,box-shadow,background-color]',
      'placeholder:text-[hsl(var(--muted-foreground))]',
      'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring))] focus-visible:ring-offset-2',
      'focus-visible:ring-offset-[hsl(var(--background))]',
      'disabled:cursor-not-allowed disabled:opacity-50',
      'aria-[invalid=true]:border-[hsl(var(--destructive))] aria-[invalid=true]:ring-[hsl(var(--destructive))]',
      props.class,
    )"
    @input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
  >
</template>

<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  modelValue?: string | number | null
  class?: HTMLAttributes['class']
}>()

const emit = defineEmits<{
  (event: 'update:modelValue', value: string): void
}>()
</script>
