// frontend/src/console/react/TokenUsageTrend.tsx
import * as React from 'react'
import type { TrendDataPoint } from '@/types'
import { readUsageNumber } from '@/utils/usageDisplay'
import {
  CartesianGrid,
  Line,
  LineChart,
  XAxis,
  YAxis,
} from 'recharts'
import { Card, CardContent, CardHeader, CardTitle } from './ui/card'
import {
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from './ui/chart'
import { Skeleton } from './ui/skeleton'

export interface TokenUsageTrendProps {
  trendData?: TrendDataPoint[] | null
  loading?: boolean
  title: string
  noData: string
}

interface TrendPoint {
  date: string
  input: number
  output: number
  cacheCreation: number
  cacheRead: number
  cacheHitRate: number
}

const chartConfig = {
  input: { label: 'Input', color: 'hsl(var(--chart-1))' },
  output: { label: 'Output', color: 'hsl(var(--chart-2))' },
  cacheCreation: { label: 'Cache Creation', color: 'hsl(var(--chart-3))' },
  cacheRead: { label: 'Cache Read', color: 'hsl(var(--chart-4))' },
  cacheHitRate: { label: 'Cache Hit Rate', color: 'hsl(var(--chart-5))' },
} satisfies ChartConfig

const formatTokens = (value: number): string => {
  if (value >= 1_000_000_000) return `${(value / 1_000_000_000).toFixed(2)}B`
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(2)}M`
  if (value >= 1_000) return `${(value / 1_000).toFixed(2)}K`
  return value.toLocaleString()
}

const normalizeTrend = (trendData?: TrendDataPoint[] | null): TrendPoint[] => (
  (trendData || []).map((point) => {
    const source = point as unknown as Record<string, unknown>
    const input = readUsageNumber(point, ['input_tokens', 'prompt_tokens'])
    const cacheCreation = readUsageNumber(point, ['cache_creation_tokens', 'cache_write_tokens'])
    const cacheRead = readUsageNumber(point, ['cache_read_tokens', 'cached_tokens'])
    const promptTokens = input + cacheCreation + cacheRead
    return {
      date: String(source.date ?? source.period ?? source.timestamp ?? ''),
      input,
      output: readUsageNumber(point, ['output_tokens', 'completion_tokens']),
      cacheCreation,
      cacheRead,
      cacheHitRate: promptTokens > 0 ? (cacheRead / promptTokens) * 100 : 0,
    }
  })
)

function TrendChart({ points }: { points: TrendPoint[] }) {
  return (
    <ChartContainer config={chartConfig} className="h-64 w-full aspect-auto">
      <LineChart accessibilityLayer data={points} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}>
        <CartesianGrid vertical={false} />
        <XAxis dataKey="date" tickLine={false} axisLine={false} tickMargin={10} minTickGap={24} />
        <YAxis yAxisId="tokens" tickLine={false} axisLine={false} tickFormatter={formatTokens} width={48} />
        <YAxis yAxisId="percent" hide domain={[0, 100]} />
        <ChartTooltip content={<ChartTooltipContent indicator="line" />} />
        <ChartLegend content={<ChartLegendContent />} />
        <Line yAxisId="tokens" dataKey="input" type="monotone" stroke="var(--color-input)" strokeWidth={2} dot={false} />
        <Line yAxisId="tokens" dataKey="output" type="monotone" stroke="var(--color-output)" strokeWidth={2} dot={false} />
        <Line yAxisId="tokens" dataKey="cacheCreation" type="monotone" stroke="var(--color-cacheCreation)" strokeWidth={2} dot={false} />
        <Line yAxisId="tokens" dataKey="cacheRead" type="monotone" stroke="var(--color-cacheRead)" strokeWidth={2} dot={false} />
        <Line yAxisId="percent" dataKey="cacheHitRate" type="monotone" stroke="var(--color-cacheHitRate)" strokeWidth={2} strokeDasharray="5 5" dot={false} />
      </LineChart>
    </ChartContainer>
  )
}

export default function TokenUsageTrend({ trendData, loading = false, title, noData }: TokenUsageTrendProps) {
  const points = normalizeTrend(trendData)

  return (
    <Card className="min-w-0 overflow-hidden">
      <CardHeader className="pb-4">
        <CardTitle className="text-base">{title}</CardTitle>
      </CardHeader>
      <CardContent className="pt-0">
        {loading ? (
          <div className="space-y-3" role="status" aria-label="Loading">
            <Skeleton className="h-64 w-full" />
          </div>
        ) : points.length > 0 ? (
          <TrendChart points={points} />
        ) : (
          <div className="flex h-64 items-center justify-center text-sm text-[hsl(var(--muted-foreground))]">{noData}</div>
        )}
      </CardContent>
    </Card>
  )
}

// frontend/src/components/charts/TokenUsageTrend.vue
<template>
  <Card class="min-w-0 overflow-hidden p-4">
    <h3 class="mb-4 text-sm font-semibold text-gray-900 dark:text-white">
      {{ t('admin.dashboard.tokenUsageTrend') }}
    </h3>
    <div v-if="loading" class="flex h-48 items-center justify-center">
      <LoadingSpinner />
    </div>
    <div v-else-if="normalizedTrend.length > 0 && chartData" class="relative h-48 min-w-0 overflow-hidden">
      <Line :data="chartData" :options="lineOptions" />
    </div>
    <div
      v-else
      class="flex h-48 items-center justify-center text-sm text-gray-500 dark:text-gray-400"
    >
      {{ t('admin.dashboard.noDataAvailable') }}
    </div>
  </Card>
</template>

<script setup lang="ts">
import { computed, markRaw } from 'vue'
import { useI18n } from 'vue-i18n'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
} from 'chart.js'
import { Line } from 'vue-chartjs'
import LoadingSpinner from '@/components/common/LoadingSpinner.vue'
import { Card } from '@/components/ui/card'
import type { TrendDataPoint } from '@/types'
import { readUsageNumber } from '@/utils/usageDisplay'

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
)

const { t } = useI18n()

const props = defineProps<{
  trendData?: TrendDataPoint[] | null
  loading?: boolean
}>()

const isDarkMode = computed(() => {
  return document.documentElement.classList.contains('dark')
})

const chartColors = computed(() => ({
  text: isDarkMode.value ? '#e5e7eb' : '#374151',
  grid: isDarkMode.value ? '#374151' : '#e5e7eb',
  input: '#262626',
  output: '#525252',
  cacheCreation: '#737373',
  cacheRead: '#a3a3a3',
  cacheHitRate: '#d4d4d4'
}))

const normalizedTrend = computed(() => (props.trendData || []).map((point) => {
  const inputTokens = readUsageNumber(point, ['input_tokens', 'prompt_tokens'])
  const outputTokens = readUsageNumber(point, ['output_tokens', 'completion_tokens'])
  const cacheCreationTokens = readUsageNumber(point, ['cache_creation_tokens', 'cache_write_tokens'])
  const cacheReadTokens = readUsageNumber(point, ['cache_read_tokens', 'cached_tokens'])

  return {
    date: String((point as unknown as Record<string, unknown>).date
      ?? (point as unknown as Record<string, unknown>).period
      ?? (point as unknown as Record<string, unknown>).timestamp
      ?? ''),
    input_tokens: inputTokens,
    output_tokens: outputTokens,
    cache_creation_tokens: cacheCreationTokens,
    cache_read_tokens: cacheReadTokens,
    cost: readUsageNumber(point, ['cost', 'total_cost', 'standard_cost']),
    actual_cost: readUsageNumber(point, ['actual_cost', 'user_cost']),
  }
}))

const chartData = computed(() => {
  if (!normalizedTrend.value.length) return null

  return markRaw({
    labels: normalizedTrend.value.map((d) => d.date),
    datasets: [
      {
        label: 'Input',
        data: normalizedTrend.value.map((d) => d.input_tokens),
        borderColor: chartColors.value.input,
        backgroundColor: `${chartColors.value.input}20`,
        fill: true,
        tension: 0.3
      },
      {
        label: 'Output',
        data: normalizedTrend.value.map((d) => d.output_tokens),
        borderColor: chartColors.value.output,
        backgroundColor: `${chartColors.value.output}20`,
        fill: true,
        tension: 0.3
      },
      {
        label: 'Cache Creation',
        data: normalizedTrend.value.map((d) => d.cache_creation_tokens),
        borderColor: chartColors.value.cacheCreation,
        backgroundColor: `${chartColors.value.cacheCreation}20`,
        fill: true,
        tension: 0.3
      },
      {
        label: 'Cache Read',
        data: normalizedTrend.value.map((d) => d.cache_read_tokens),
        borderColor: chartColors.value.cacheRead,
        backgroundColor: `${chartColors.value.cacheRead}20`,
        fill: true,
        tension: 0.3
      },
      {
        label: 'Cache Hit Rate',
        data: normalizedTrend.value.map((d) => {
          const totalPromptTokens = d.input_tokens + d.cache_read_tokens + d.cache_creation_tokens
          return totalPromptTokens > 0 ? (d.cache_read_tokens / totalPromptTokens) * 100 : 0
        }),
        borderColor: chartColors.value.cacheHitRate,
        backgroundColor: `${chartColors.value.cacheHitRate}20`,
        borderDash: [5, 5],
        fill: false,
        tension: 0.3,
        yAxisID: 'yPercent'
      }
    ]
  })
})

const lineOptions = computed(() => markRaw({
  responsive: true,
  maintainAspectRatio: false,
  interaction: {
    intersect: false,
    mode: 'index' as const
  },
  plugins: {
    legend: {
      position: 'top' as const,
      labels: {
        color: chartColors.value.text,
        usePointStyle: true,
        pointStyle: 'circle',
        padding: 15,
        font: {
          size: 11
        }
      }
    },
    tooltip: {
      callbacks: {
        label: (context: any) => {
          if (context.dataset.yAxisID === 'yPercent') {
            return `${context.dataset.label}: ${context.raw.toFixed(1)}%`
          }
          return `${context.dataset.label}: ${formatTokens(context.raw)}`
        },
        footer: (tooltipItems: any) => {
          const dataIndex = tooltipItems[0]?.dataIndex
          if (dataIndex !== undefined && normalizedTrend.value[dataIndex]) {
            const data = normalizedTrend.value[dataIndex]
            return `Actual: $${formatCost(data.actual_cost)} | Standard: $${formatCost(data.cost)}`
          }
          return ''
        }
      }
    }
  },
  scales: {
    x: {
      grid: {
        color: chartColors.value.grid
      },
      ticks: {
        color: chartColors.value.text,
        font: {
          size: 10
        }
      }
    },
    y: {
      grid: {
        color: chartColors.value.grid
      },
      ticks: {
        color: chartColors.value.text,
        font: {
          size: 10
        },
        callback: (value: string | number) => formatTokens(Number(value))
      }
    },
    yPercent: {
      position: 'right' as const,
      min: 0,
      max: 100,
      grid: {
        drawOnChartArea: false
      },
      ticks: {
        color: chartColors.value.cacheHitRate,
        font: {
          size: 10
        },
        callback: (value: string | number) => `${value}%`
      }
    }
  }
}))

const formatTokens = (value: number): string => {
  if (value >= 1_000_000_000) {
    return `${(value / 1_000_000_000).toFixed(2)}B`
  } else if (value >= 1_000_000) {
    return `${(value / 1_000_000).toFixed(2)}M`
  } else if (value >= 1_000) {
    return `${(value / 1_000).toFixed(2)}K`
  }
  return value.toLocaleString()
}

const formatCost = (value: number): string => {
  if (value >= 1000) {
    return (value / 1000).toFixed(2) + 'K'
  } else if (value >= 1) {
    return value.toFixed(2)
  } else if (value >= 0.01) {
    return value.toFixed(3)
  }
  return value.toFixed(4)
}
</script>
